### ISSUE TITLE
newUserTaskAssignCommand error

### ISSUE THREAD

**Issue by KricYi** [quarkiverse/quarkus-zeebe#286]
Hi:
  It's nice to be able to use the latest zeebe assignment user task , thank you very much.
   No problem completing tasks, I encountered some problems when I assigned user task, here is my code.Based on the exception, it appears that my configured quarkus.zeebe.client.broker.gateway-address does not work for the newUserTaskAssign Command method.

```
zeebeClient.newUserTaskAssignCommand(transferDTO.getTaskId())
                .assignee(transferDTO.getAssignee().getUserId().toString())
                .allowOverride(true)
                .send().join();
```
This is the error message for quarkus:dev runtime

```
Error Info: io.camunda.zeebe.client.api.command.ClientException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://0.0.0.0:8080 [/0.0.0.0] failed: Connection refused: getsockopt: java.util.concurrent.CompletionException: io.camunda.zeebe.client.api.command.ClientException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://0.0.0.0:8080 [/0.0.0.0] failed: Connection refused: getsockopt
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService.transferTicket(TicketService.java:146)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_Subclass.transferTicket$$superforward(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_Subclass$$function$$9.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at com.xyinsights.aiyixiao.runner.MethodLoggingInterceptor.logMethodInvocation(MethodLoggingInterceptor.java:84)
	at com.xyinsights.aiyixiao.runner.MethodLoggingInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_Subclass.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_ClientProxy.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter.transferTicket(TicketAdapter.java:106)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_Subclass.transferTicket$$superforward(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_Subclass$$function$$18.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_Subclass.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_ClientProxy.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter$quarkusrestinvoker$transferTicket_68e077015affcff6a0ad215d00be051abf98e37c.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.camunda.zeebe.client.api.command.ClientException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://0.0.0.0:8080 [/0.0.0.0] failed: Connection refused: getsockopt
	at io.camunda.zeebe.client.impl.http.ApiCallback.failed(ApiCallback.java:69)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1.failed(InternalAbstractHttpAsyncClient.java:326)
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec$1.failed(AsyncRedirectExec.java:246)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec$1.failed(AsyncHttpRequestRetryExec.java:168)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec$1.failed(AsyncProtocolExec.java:295)
	at org.apache.hc.client5.http.impl.async.AsyncConnectExec$2.failed(AsyncConnectExec.java:214)
	at org.apache.hc.core5.concurrent.CallbackContribution.failed(CallbackContribution.java:47)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.nio.PoolingAsyncClientConnectionManager$4.failed(PoolingAsyncClientConnectionManager.java:481)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.nio.DefaultAsyncClientConnectionOperator$1.failed(DefaultAsyncClientConnectionOperator.java:140)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.nio.MultihomeIOSessionRequester$2$1.failed(MultihomeIOSessionRequester.java:161)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.reactor.IOSessionRequest.failed(IOSessionRequest.java:78)
	at org.apache.hc.core5.reactor.InternalConnectChannel.onException(InternalConnectChannel.java:108)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:55)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	... 1 more
Caused by: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://0.0.0.0:8080 [/0.0.0.0] failed: Connection refused: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at org.apache.hc.core5.reactor.InternalConnectChannel.onIOEvent(InternalConnectChannel.java:70)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	... 5 more
```

**Comment by KricYi** [comment]
After jar runs, exception messages send changes
```
io.camunda.zeebe.client.api.command.ClientException: java.lang.NullPointerException: must specify a response: java.util.concurrent.CompletionException: io.camunda.zeebe.client.api.command.ClientException: java.lang.NullPointerException: must specify a response
	at java.base@21.0.2/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base@21.0.2/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService.transferTicket(TicketService.java:146)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_Subclass.transferTicket$$superforward(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_Subclass$$function$$9.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at com.xyinsights.aiyixiao.runner.MethodLoggingInterceptor.logMethodInvocation(MethodLoggingInterceptor.java:84)
	at com.xyinsights.aiyixiao.runner.MethodLoggingInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_Subclass.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.app.service.TicketService_ClientProxy.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter.transferTicket(TicketAdapter.java:106)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_Subclass.transferTicket$$superforward(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_Subclass$$function$$18.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_Subclass.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter_ClientProxy.transferTicket(Unknown Source)
	at com.xyinsights.aiyixiao.ticket.adapter.app.TicketAdapter$quarkusrestinvoker$transferTicket_68e077015affcff6a0ad215d00be051abf98e37c.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: io.camunda.zeebe.client.api.command.ClientException: java.lang.NullPointerException: must specify a response
	at io.camunda.zeebe.client.impl.http.ApiCallback.failed(ApiCallback.java:69)
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1.failed(InternalAbstractHttpAsyncClient.java:326)
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec$1.failed(AsyncRedirectExec.java:246)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec$1.failed(AsyncHttpRequestRetryExec.java:168)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec$1.failed(AsyncProtocolExec.java:295)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.failed(HttpAsyncMainClientExec.java:131)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.failed(ClientHttp1StreamHandler.java:285)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.terminate(ClientHttp1StreamDuplexer.java:181)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.shutdownSession(AbstractHttp1StreamDuplexer.java:164)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onException(AbstractHttp1StreamDuplexer.java:404)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.exception(AbstractHttp1IOEventHandler.java:90)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.exception(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.InternalDataChannel.onException(InternalDataChannel.java:180)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:55)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	... 4 more
Caused by: java.lang.NullPointerException: must specify a response
	at java.base@21.0.2/java.util.Objects.requireNonNull(Objects.java:259)
	at io.camunda.zeebe.client.impl.http.ApiEntity$Response.<init>(ApiEntity.java:89)
	at io.camunda.zeebe.client.impl.http.ApiEntity$Response.<init>(ApiEntity.java:85)
	at io.camunda.zeebe.client.impl.http.ApiEntity.of(ApiEntity.java:74)
	at io.camunda.zeebe.client.impl.http.ApiEntityConsumer.generateContent(ApiEntityConsumer.java:97)
	at io.camunda.zeebe.client.impl.http.ApiEntityConsumer.generateContent(ApiEntityConsumer.java:49)
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:82)
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:81)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:142)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:251)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:270)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:366)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:335)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	... 8 more
```

**Comment by andrejpetras** [comment]
Hi @KricYi, 

The property `quarkus.zeebe.client.broker.gateway-address` is only used for the GRPC call.
For the rest call API you also need to set up `quarkus.zeebe.client.broker.rest-address`.

Source code:
https://github.com/quarkiverse/quarkus-zeebe/blob/main/runtime/src/main/java/io/quarkiverse/zeebe/runtime/ZeebeClientBuilderFactory.java#L14C44-L14C55

According to my information, the Zeebe is switching from GRPC to HTTP client, but that will take some time.
For this reason, multiple endpoints must be configured.

For now, please also try to configure the `quarkus.zeebe.client.broker.rest-address` property.

**Comment by KricYi** [comment]
Hi, @andrejpetras 
 Thank you very much.
